### ISSUE TITLE
post icons

### ISSUE THREAD

**Issue by ashutoshmjain** [jarrekk/jalpc_jekyll_theme#49]
Hi Jack 
While building the posts , I noticed that there is an icon for each category you are using . Wondering if I could create icons for my categories ?  Where are these icons stored  ? 

Thanks in advance 

Ashutosh

**Comment by jarrekk** [comment]
Hi @ashutoshmjain 

I use icon at **about me** section at index page and blog page, the config is at:

* **about me**: `_config.yml` `author` item in the newest commit. But you can edit them in `_includes/sections/about.html`, code block starts with `<div class="col-xs-2 wow fadeInLeft">`

* **blog page**: I write them at each post's metadata at dir `_posts/`, there is a `icon` item

All icons are quoted to lib [fontawesome](http://fontawesome.io/icons/) and [font-mfizzed](http://fizzed.com/oss/font-mfizz), you can find icon you like and paste icon code to preceding place, when use **fontawesome** icons, code should be `fa-barcode` if icon code is `barcode`
![image](https://cloud.githubusercontent.com/assets/10969478/22450138/a09df67e-e79f-11e6-87fc-e8078d2ba851.png)
**font-mfizze** icon code is `icon-xxx` just use it :) 

Thanks

Jack

**Comment by ashutoshmjain** [comment]
Thanks Jack - I will check it out   

Much appreciated

Ashutosh

**Comment by ShashwatHiregoudar** [comment]
@jarrekk CAn you tell me how to upgrade the fontawesome version also
because some of the new icons are not there in the list
